const familyData = [
  {
    "FamID": 1,
    "Couple ID": 1,
    "Gen ID": 1,
    "Name": "Paul",
    "Middle name": "",
    "Preferred name": "Paul",
    "Surname": "Moroka",
    "Gender": "Male",
    "Date of birth": "5 October 1940",
    "Place of birth": "Rustenburg, North West",
    "Child to": "-",
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 2,
    "Couple ID": 2,
    "Gen ID": 2,
    "Name": "Archie",
    "Middle name": "",
    "Preferred name": "Archie",
    "Surname": "Moroka",
    "Gender": "Male",
    "Date of birth": "1 February 1968",
    "Place of birth": "Johannesburg, Gauteng",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 3,
    "Couple ID": 3,
    "Gen ID": 2,
    "Name": "Busang",
    "Middle name": "",
    "Preferred name": "Busang",
    "Surname": "Moroka",
    "Gender": "Male",
    "Date of birth": "2 February 1969",
    "Place of birth": "Johannesburg, Gauteng",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 4,
    "Couple ID": 4,
    "Gen ID": 2,
    "Name": "Karabo",
    "Middle name": "",
    "Preferred name": "Karabo",
    "Surname": "Moroka",
    "Gender": "Female",
    "Date of birth": "10 June 1970",
    "Place of birth": "Johannesburg, Gauteng",
    "Child to": 1,
    "Paired with": 6,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 5,
    "Couple ID": 5,
    "Gen ID": 2,
    "Name": "Zakes",
    "Middle name": "",
    "Preferred name": "Zakes",
    "Surname": "Moroka",
    "Gender": "Male",
    "Date of birth": "7 September 1975",
    "Place of birth": "Pretoria, Gauteng",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 6,
    "Couple ID": 4,
    "Gen ID": 2,
    "Name": "Tau",
    "Middle name": "",
    "Preferred name": "Tau",
    "Surname": "Mogale",
    "Gender": "Male",
    "Date of birth": "11 July 1967",
    "Place of birth": "Bloemfontein, Free State",
    "Child to": "-",
    "Paired with": 4,
    "Marital status": "Marrried",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 7,
    "Couple ID": 6,
    "Gen ID": 3,
    "Name": "Mazwi",
    "Middle name": "",
    "Preferred name": "Mazwi",
    "Surname": "Moroka",
    "Gender": "Male",
    "Date of birth": "31 March 1991",
    "Place of birth": "Johannesburg, Gauteng",
    "Child to": 2,
    "Paired with": 9,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 8,
    "Couple ID": "-",
    "Gen ID": 3,
    "Name": "Smanga",
    "Middle name": "",
    "Preferred name": "Smanga",
    "Surname": "Moroka",
    "Gender": "Male",
    "Date of birth": "22 November 1994",
    "Place of birth": "Johannesburg, Gauteng",
    "Child to": 2,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 9,
    "Couple ID": 6,
    "Gen ID": 3,
    "Name": "Dr. Sphesihle",
    "Middle name": "",
    "Preferred name": "Sphe",
    "Surname": "Cele",
    "Gender": "Male",
    "Date of birth": "10 April 1996",
    "Place of birth": "Durban, KwaZulu-Natal",
    "Child to": "-",
    "Paired with": 7,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  },
  {
    "FamID": 10,
    "Couple ID": "-",
    "Gen ID": 4,
    "Name": "Rorisang",
    "Middle name": "",
    "Preferred name": "Rorisang",
    "Surname": "Moroka",
    "Gender": "Female",
    "Date of birth": "28 January 2022",
    "Place of birth": "Johannesburg, Gauteng",
    "Child to": 6,
    "Paired with": "-",
    "Marital status": "Signle",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE",
    "LinkedIn": "",
    "Facebook": "",
    "Twitter": "",
    "YouTube": "",
    "Tik-Tok": "",
    "Snapchat": "",
    "WhatsApp": ""
  }
];
