const familyData = [
  {
    "FamID": 1,
    "Couple ID": 1,
    "Gen ID": 1,
    "Name": "Makasani",
    "Middle name": "David I",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 2,
    "Marital status": "Married",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 2,
    "Couple ID": 1,
    "Gen ID": 1,
    "Name": "Maria",
    "Middle name": "",
    "Surname": "Nkuna",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 1,
    "Marital status": "Married",
    "Alive / deceased": "Deceased",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 3,
    "Couple ID": 2,
    "Gen ID": 2,
    "Name": "Hlengani",
    "Middle name": "Abel",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "1 January 1909",
    "Place of birth": "Venda, Limpopo",
    "Date of death": "",
    "Child to": 1,
    "Paired with": 10,
    "Marital status": "Married",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 4,
    "Couple ID": "-",
    "Gen ID": 2,
    "Name": "Phillip",
    "Middle name": "",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 5,
    "Couple ID": "-",
    "Gen ID": 2,
    "Name": "Thomas",
    "Middle name": "",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 6,
    "Couple ID": "-",
    "Gen ID": 2,
    "Name": "John",
    "Middle name": "",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 7,
    "Couple ID": "-",
    "Gen ID": 2,
    "Name": "Samuel",
    "Middle name": "",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 8,
    "Couple ID": "-",
    "Gen ID": 2,
    "Name": "Paul",
    "Middle name": "",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 9,
    "Couple ID": "-",
    "Gen ID": 2,
    "Name": "Matthew",
    "Middle name": "",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 1,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 10,
    "Couple ID": 2,
    "Gen ID": 2,
    "Name": "Danisa",
    "Middle name": "Juliana",
    "Surname": "Ndhambi",
    "Gender": "Female",
    "Date of birth": "1 January 1927",
    "Place of birth": "Tlangelani, Mudabula, Limpopo",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 3,
    "Marital status": "Married",
    "Alive / deceased": "Deceased",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 11,
    "Couple ID": "-",
    "Gen ID": 3,
    "Name": "Makasani",
    "Middle name": "David II",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "4 March 1954",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 2,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 12,
    "Couple ID": 3,
    "Gen ID": 3,
    "Name": "N'wativa",
    "Middle name": "Annah",
    "Surname": "Jeleni",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 2,
    "Paired with": "",
    "Marital status": "Married",
    "Alive / deceased": "Deceased",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 13,
    "Couple ID": 4,
    "Gen ID": 3,
    "Name": "Mafemani",
    "Middle name": "Isaiah",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "18 May 1959",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 2,
    "Paired with": "",
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 14,
    "Couple ID": 5,
    "Gen ID": 3,
    "Name": "Rhulani",
    "Middle name": "Patricia",
    "Surname": "Jeleni",
    "Gender": "Female",
    "Date of birth": "25 January 1962",
    "Place of birth": "Tlangelani, Mudabula, Limpopo",
    "Date of death": "",
    "Child to": 2,
    "Paired with": "",
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 15,
    "Couple ID": 6,
    "Gen ID": 3,
    "Name": "Tintswalo",
    "Middle name": "Helen",
    "Surname": "Jeleni",
    "Gender": "Female",
    "Date of birth": "4 July 1965",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 2,
    "Paired with": "",
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 16,
    "Couple ID": 3,
    "Gen ID": 3,
    "Name": "Mveyi",
    "Middle name": "S",
    "Surname": "Nxumalo",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 12,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 17,
    "Couple ID": 4,
    "Gen ID": 3,
    "Name": "Elizabeth",
    "Middle name": "",
    "Surname": "Chauke",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 13,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 18,
    "Couple ID": 5,
    "Gen ID": 3,
    "Name": "Khaziyeni",
    "Middle name": "Patrick",
    "Surname": "Ntimane",
    "Gender": "Male",
    "Date of birth": "22 August 1959",
    "Place of birth": "Nkuri-Sifasonke, Greater Giyani, Limpopo",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 14,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 19,
    "Couple ID": 6,
    "Gen ID": 3,
    "Name": "Murimisi",
    "Middle name": "Simon",
    "Surname": "Makaringe",
    "Gender": "Male",
    "Date of birth": "4 December 1960",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 15,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 20,
    "Couple ID": 7,
    "Gen ID": 4,
    "Name": "Lorraine",
    "Middle name": "Tinyiko",
    "Surname": "Nxumalo",
    "Gender": "Female",
    "Date of birth": "8 February 1980",
    "Place of birth": "Thulamahashe, Bushbuckridge, Mpumalanga",
    "Date of death": "",
    "Child to": 3,
    "Paired with": 36,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 21,
    "Couple ID": 8,
    "Gen ID": 4,
    "Name": "Cyril",
    "Middle name": "",
    "Surname": "Nxumalo",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 3,
    "Paired with": 37,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 22,
    "Couple ID": 9,
    "Gen ID": 4,
    "Name": "Charles",
    "Middle name": "",
    "Surname": "Nxumalo",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 3,
    "Paired with": 38,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 23,
    "Couple ID": 10,
    "Gen ID": 4,
    "Name": "Busisiwe",
    "Middle name": "Charmaine",
    "Surname": "Nxumalo",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 3,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 24,
    "Couple ID": 11,
    "Gen ID": 4,
    "Name": "Innocent",
    "Middle name": "Mzwandile",
    "Surname": "Nxumalo",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 3,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 25,
    "Couple ID": 12,
    "Gen ID": 4,
    "Name": "Bongani",
    "Middle name": "",
    "Surname": "Nxumalo",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 3,
    "Paired with": 39,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 26,
    "Couple ID": "-",
    "Gen ID": 4,
    "Name": "Themba",
    "Middle name": "A",
    "Surname": "Jeleni",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 4,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 27,
    "Couple ID": 13,
    "Gen ID": 4,
    "Name": "Nyeleti",
    "Middle name": "Angel",
    "Surname": "Ntimane",
    "Gender": "Female",
    "Date of birth": "23 January 1983",
    "Place of birth": "Elim, Louis Trichardt, Limpopo",
    "Date of death": "",
    "Child to": 5,
    "Paired with": 40,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 28,
    "Couple ID": 14,
    "Gen ID": 4,
    "Name": "Ntsakisi",
    "Middle name": "Rejoice",
    "Surname": "Ntimane",
    "Gender": "Female",
    "Date of birth": "13 January 1988",
    "Place of birth": "Giyani, Greater Giyani, Limpopo",
    "Date of death": "",
    "Child to": 5,
    "Paired with": 41,
    "Marital status": "Divorced",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 29,
    "Couple ID": 15,
    "Gen ID": 4,
    "Name": "Cindy",
    "Middle name": "P",
    "Surname": "Ntimane",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 5,
    "Paired with": 42,
    "Marital status": "Unmarried",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 30,
    "Couple ID": 16,
    "Gen ID": 4,
    "Name": "Jessica",
    "Middle name": "",
    "Surname": "Makaringe",
    "Gender": "Female",
    "Date of birth": "15 October 1984",
    "Place of birth": "Chiawelo, Soweto, Gauteng",
    "Date of death": "",
    "Child to": 6,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 31,
    "Couple ID": 17,
    "Gen ID": 4,
    "Name": "Fumani",
    "Middle name": "",
    "Surname": "Makaringe",
    "Gender": "Female",
    "Date of birth": "23 March 1990",
    "Place of birth": "Chiawelo, Soweto, Gauteng",
    "Date of death": "",
    "Child to": 6,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 32,
    "Couple ID": 18,
    "Gen ID": 4,
    "Name": "Mikateko",
    "Middle name": "Sandile",
    "Surname": "Makaringe",
    "Gender": "Male",
    "Date of birth": "29 July 1994",
    "Place of birth": "Chiawelo, Soweto, Gauteng",
    "Date of death": "",
    "Child to": 6,
    "Paired with": 43,
    "Marital status": "Engaged",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 33,
    "Couple ID": "-",
    "Gen ID": 4,
    "Name": "Lebogang",
    "Middle name": "",
    "Surname": "Makaringe",
    "Gender": "Male",
    "Date of birth": "29 May 1996",
    "Place of birth": "Chiawelo, Soweto, Gauteng",
    "Date of death": "",
    "Child to": 6,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 34,
    "Couple ID": "-",
    "Gen ID": 4,
    "Name": "Nyiko",
    "Middle name": "",
    "Surname": "Makaringe",
    "Gender": "Male",
    "Date of birth": "9 January 1999",
    "Place of birth": "Roodepoort, Johannesburg, Gauteng",
    "Date of death": "",
    "Child to": 6,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 35,
    "Couple ID": "-",
    "Gen ID": 4,
    "Name": "Murimisi",
    "Middle name": "Simon Jr",
    "Surname": "Makaringe",
    "Gender": "Male",
    "Date of birth": "15 March 2001",
    "Place of birth": "Roodepoort, Johannesburg, Gauteng",
    "Date of death": "",
    "Child to": 6,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 36,
    "Couple ID": 7,
    "Gen ID": 4,
    "Name": "Masiza",
    "Middle name": "S",
    "Surname": "Mkansi",
    "Gender": "Male",
    "Date of birth": "2 March 1974",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 20,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 37,
    "Couple ID": 8,
    "Gen ID": 4,
    "Name": "Sphiwe",
    "Middle name": "",
    "Surname": "Sibiya",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 21,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 38,
    "Couple ID": 9,
    "Gen ID": 4,
    "Name": "Zanele",
    "Middle name": "",
    "Surname": "Ntimane",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 22,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 39,
    "Couple ID": 12,
    "Gen ID": 4,
    "Name": "Tinyiko",
    "Middle name": "B",
    "Surname": "Mathebula",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 25,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 40,
    "Couple ID": 13,
    "Gen ID": 4,
    "Name": "Nicol",
    "Middle name": "Judas",
    "Surname": "Mkhacana",
    "Gender": "Male",
    "Date of birth": "29 January 1982",
    "Place of birth": "Tzaneen, Limpopo",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 27,
    "Marital status": "Married",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 41,
    "Couple ID": 14,
    "Gen ID": 4,
    "Name": "Tommy",
    "Middle name": "",
    "Surname": "Shilubane",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 28,
    "Marital status": "Divorced",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 42,
    "Couple ID": 15,
    "Gen ID": 4,
    "Name": "Cathrada",
    "Middle name": "",
    "Surname": "Mkansi",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 29,
    "Marital status": "Unmarried",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 43,
    "Couple ID": 18,
    "Gen ID": 4,
    "Name": "Nombuso",
    "Middle name": "",
    "Surname": "Vilakazi",
    "Gender": "Female",
    "Date of birth": "27 April 1995",
    "Place of birth": "Umlazi, Durban, KwaZulu-Natal",
    "Date of death": "",
    "Child to": "-",
    "Paired with": 32,
    "Marital status": "Engaged",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 44,
    "Couple ID": 19,
    "Gen ID": 5,
    "Name": "Ndzalama",
    "Middle name": "Rito",
    "Surname": "Mkansi",
    "Gender": "Female",
    "Date of birth": "17 Dec 2003",
    "Place of birth": "Louis Trichardt, Limpopo",
    "Date of death": "",
    "Child to": 7,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 45,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Vukosi",
    "Middle name": "",
    "Surname": "Mkansi",
    "Gender": "Male",
    "Date of birth": "1 July 2009",
    "Place of birth": "Louis Trichardt, Limpopo",
    "Date of death": "",
    "Child to": 7,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 46,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Lulama",
    "Middle name": "",
    "Surname": "Nxumalo",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 8,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 47,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Kevin",
    "Middle name": "",
    "Surname": "Nxumalo",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 8,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 48,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Nkateko",
    "Middle name": "",
    "Surname": "Nxumalo",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 8,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 49,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Khanyisa",
    "Middle name": "N",
    "Surname": "Mnisi",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 9,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 50,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Ntsakelo",
    "Middle name": "Best",
    "Surname": "Madlophe",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 10,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 51,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Zukile",
    "Middle name": "Innocent",
    "Surname": "Nxumalo",
    "Gender": "Male",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 11,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 52,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Zoe",
    "Middle name": "Rirhandzu",
    "Surname": "Mkhacana",
    "Gender": "Female",
    "Date of birth": "11 February 2011",
    "Place of birth": "Pretoria, Gauteng",
    "Date of death": "",
    "Child to": 13,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 53,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Akani",
    "Middle name": "Nonwabe",
    "Surname": "Mkhacana",
    "Gender": "Male",
    "Date of birth": "10 June 2013",
    "Place of birth": "Waterfall, Johannesburg, Gauteng",
    "Date of death": "",
    "Child to": 13,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 54,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Ntando",
    "Middle name": "Boniface Ntokoto",
    "Surname": "Mkhacana",
    "Gender": "Male",
    "Date of birth": "4 August 2013",
    "Place of birth": "Johannesburg, Gauteng",
    "Date of death": "",
    "Child to": 13,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "FALSE"
  },
  {
    "FamID": 55,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Mahlahle",
    "Middle name": "",
    "Surname": "Mkhacana",
    "Gender": "Male",
    "Date of birth": "31 August 2018",
    "Place of birth": "Sunninghill, Johannesburg, Gauteng",
    "Date of death": "",
    "Child to": 13,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 56,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Nganakana",
    "Middle name": "",
    "Surname": "Mkhacana",
    "Gender": "Male",
    "Date of birth": "7 January 2021",
    "Place of birth": "Saxonworld, Johannesburg, Gauteng",
    "Date of death": "",
    "Child to": 13,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 57,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Vunene",
    "Middle name": "Tommy Junior (TJ)",
    "Surname": "Shilubane",
    "Gender": "Male",
    "Date of birth": "22 May 2008",
    "Place of birth": "Giyani, Greater Giyani, Limpopo",
    "Date of death": "",
    "Child to": 14,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 58,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Risima",
    "Middle name": "Timmy",
    "Surname": "Shilubane",
    "Gender": "Male",
    "Date of birth": "13 July 2015",
    "Place of birth": "Johannesburg, Gauteng",
    "Date of death": "",
    "Child to": 14,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 59,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Kuhlula",
    "Middle name": "B",
    "Surname": "Mkansi",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 15,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 60,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Hlurile",
    "Middle name": "KX",
    "Surname": "Mkansi",
    "Gender": "Female",
    "Date of birth": "",
    "Place of birth": "",
    "Date of death": "",
    "Child to": 15,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 61,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Tadiwa",
    "Middle name": "Botshelo",
    "Surname": "Makaringe",
    "Gender": "Male",
    "Date of birth": "14 May 2011",
    "Place of birth": "Giyani, Greater Giyani, Limpopo",
    "Date of death": "",
    "Child to": 16,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 62,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Yinhla",
    "Middle name": "Singita",
    "Surname": "Makaringe",
    "Gender": "Female",
    "Date of birth": "22 September 2015",
    "Place of birth": "Giyani, Greater Giyani, Limpopo",
    "Date of death": "",
    "Child to": 16,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 63,
    "Couple ID": "-",
    "Gen ID": 5,
    "Name": "Vukona",
    "Middle name": "Luniko",
    "Surname": "Makaringe",
    "Gender": "Male",
    "Date of birth": "30 October 2014",
    "Place of birth": "Giyani, Greater Giyani, Limpopo",
    "Date of death": "",
    "Child to": 17,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  },
  {
    "FamID": 64,
    "Couple ID": "-",
    "Gen ID": 6,
    "Name": "Kuhlula",
    "Middle name": "Theo",
    "Surname": "Mkansi",
    "Gender": "Male",
    "Date of birth": "12 September 2022",
    "Place of birth": "Louis Trichardt, Limpopo",
    "Date of death": "",
    "Child to": 19,
    "Paired with": "-",
    "Marital status": "Single",
    "Alive / deceased": "Living",
    "Bloodline": "TRUE"
  }
];